# Generated by Django 5.2.3 on 2025-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='nickname#1', max_length=15),
            preserve_default=False,
        ),
    ]
