# Generated by Django 5.2.3 on 2025-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bottom_measurement_top_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom_measurement',
            name='Hip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottom_measurement',
            name='Knee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottom_measurement',
            name='Lap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottom_measurement',
            name='Length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottom_measurement',
            name='Round_Ankle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottom_measurement',
            name='Waist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Arm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Back_or_Shoulder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Chest_or_Burst',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Hand',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Neck',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='top_measurement',
            name='Stomach',
            field=models.IntegerField(),
        ),
    ]
