# Generated by Django 5.2.3 on 2025-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottom_measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Waist', models.IntegerField(max_length=3)),
                ('Lap', models.IntegerField(max_length=3)),
                ('Hip', models.IntegerField(max_length=3)),
                ('Knee', models.IntegerField(max_length=3)),
                ('Length', models.IntegerField(max_length=3)),
                ('Round_Ankle', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='top_measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Back_or_Shoulder', models.IntegerField(max_length=3)),
                ('Chest_or_Burst', models.IntegerField(max_length=3)),
                ('Stomach', models.IntegerField(max_length=3)),
                ('Length', models.IntegerField(max_length=3)),
                ('Neck', models.IntegerField(max_length=3)),
                ('Hand', models.IntegerField(max_length=3)),
                ('Arm', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='local_gov_area',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
