# Generated by Django 5.2.3 on 2025-07-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_bottom_measurement_hip_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bottom_measurement',
            new_name='BottomMeasurement',
        ),
        migrations.RenameModel(
            old_name='top_measurement',
            new_name='TopMeasurement',
        ),
    ]
