# Generated by Django 5.2.3 on 2025-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(blank=True, default=0, max_length=6),
            preserve_default=False,
        ),
    ]
