# Generated by Django 5.2.3 on 2025-08-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
