# Generated by Django 5.2.3 on 2025-08-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('SHIPPING', 'Shipping'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
